---
title: "Лекция 5. Гетероскедастичность"
output:
  ioslides_presentation: default
  beamer_presentation:
    includes:
      in_header: header.tex
    keep_tex: yes
---

## Метод максимального правдоподобия

Для проверки гипотез мы предполагали условную гомоскедастичность ошибок:

$ E(\varepsilon_i | X)=\sigma^2 $

Что произойдет если эта предпосылка будет нарушена?

## Разница между условной и безусловной гетероскедастичностью



## Проблема:

Все остальные предпосылки классической модели со стохастическими регрессорами для случайной выборки выполнены.

Мы используем прежние формулы:

$\hat{\beta}=(X'X)^{-1}X'y$

$\widehat{Var}(\hat{\beta})=$

В частности, $\widehat{Var}(\hat{\beta}_j)=\frac{\hat{\sigma}^2}{RSS_j}$




## Свойства для конечных выборок:

Без требования нормальности $\varepsilon$

* Линейность по $y$

* Условная несмещенность, $E(\hat{\beta}|X)=\beta$

* (---) Оценки неэффективны

## С требованием нормальности $\varepsilon$

* (---) $t=\frac{\hat{\beta}_j-\beta_j}{se(\hat{\beta}_j)} | X \sim t_{n-k}$

* (---) $RSS/\sigma^2 |X \sim \chi^2_{n-k}$

## Асимптотические свойства:




